# Generated by Django 3.1.1 on 2020-09-21 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provice', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('postCode', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=11)),
                ('cardNumber', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
