# Generated by Django 3.1.1 on 2020-10-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_promocode'),
        ('users', '0002_auto_20200922_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='used_promocodes',
            field=models.ManyToManyField(to='checkout.Promocode'),
        ),
    ]
