# Generated by Django 3.1.1 on 2020-10-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20201003_1316'),
        ('users', '0007_auto_20201004_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='used_promocodes',
            field=models.ManyToManyField(to='checkout.PromoCode'),
        ),
    ]
