# Generated by Django 3.1.1 on 2020-10-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200929_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('expirationDate', models.DateTimeField()),
                ('min_price', models.IntegerField()),
            ],
        ),
    ]
