# Generated by Django 3.1.1 on 2020-10-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='min_price',
            field=models.BigIntegerField(),
        ),
    ]
