# Generated by Django 3.1.1 on 2020-10-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20201001_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='promo_discount',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
