# Generated by Django 3.1.1 on 2020-10-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_promocode_promo_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
