# Generated by Django 3.1.1 on 2020-10-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
