# Generated by Django 3.1.1 on 2020-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_promo_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo_discount',
            field=models.IntegerField(default=0),
        ),
    ]
