# Generated by Django 3.1.1 on 2020-10-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_order_promo_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_canceled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='processing',
        ),
        migrations.AddField(
            model_name='order',
            name='promo_discount',
            field=models.IntegerField(default=0),
        ),
    ]
