# Generated by Django 3.1.1 on 2020-10-03 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20201003_1316'),
        ('cart', '0007_auto_20201003_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.promocode'),
        ),
    ]
