# Generated by Django 3.1.1 on 2020-10-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20201003_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_discripton',
            field=models.TextField(blank=True, null=True),
        ),
    ]
