# Generated by Django 3.1.1 on 2020-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='card_image',
            field=models.ImageField(default='default.jpg', upload_to='product_photos'),
        ),
    ]
