# Generated by Django 3.1.1 on 2020-09-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200926_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProducts',
        ),
    ]
