# Generated by Django 3.1.1 on 2020-10-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201002_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product_item',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='product_item',
        ),
    ]
