# Generated by Django 3.1.1 on 2020-10-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201002_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='products.Comment'),
        ),
    ]
