# Generated by Django 3.1.1 on 2020-10-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201002_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(blank=True, to='products.Comment'),
        ),
    ]
