# Generated by Django 3.1.1 on 2020-10-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201002_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subCategories',
            field=models.ManyToManyField(blank=True, to='products.SubCategory'),
        ),
    ]
