# Generated by Django 3.1.1 on 2020-10-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20201006_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='product',
            new_name='item',
        ),
        migrations.AddField(
            model_name='product',
            name='varients',
            field=models.ManyToManyField(to='products.Sku'),
        ),
    ]
