# Generated by Django 3.1.1 on 2020-10-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20201006_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='varients',
        ),
    ]
