# Generated by Django 3.1.1 on 2020-10-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_product_varients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.BigIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Sku',
        ),
    ]
